### PR TITLE
Use `open` instead of `file` for compatibility reasons

### LINKED ISSUE #3: Instalation fails
When running `pip install tiddlywebplugins.status` (or trying to install anything that depends on it, like `tiddlywebwiki`, I get the following error message:

```
Collecting tiddlywebplugins.status
  Using cached tiddlywebplugins.status-0.8.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-pzwgu_3k/tiddlywebplugins.status/setup.py", line 12, in <module>
        long_description=file(os.path.join(os.path.dirname(__file__), 'README')).read(),
    NameError: name 'file' is not defined
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-pzwgu_3k/tiddlywebplugins.status/
```

I have a PR for this momentarily. :wink:

### PR DESCRIPTION
**Pull request by JulianKniephoff**
Fixes #3

### CODE REVIEW

**Comment by cdent** [comment]
Thanks, good catch. Just out of curiosity, what are you doing with tiddlyweb and status?

**Comment by JulianKniephoff** [comment]
Not much, yet. I wanted to play around tiddlyweb to see whether I could use it as the datastore for my TiddlyWiki. I'm particularly interested in enabling other, external applications to access that data via the HTTP API.

However, I haven't gotten that far yet since I could not even install `tiddlywebwiki` because `status` is a dependency of that. ^.^

**Comment by cdent** [comment]
If you're using tiddlywiki 5 you don't need or want tiddlywebwiki, just tiddlyweb. tiddlywebwiki is for tiddlywiki classic.

There's a pull request on tiddlywiki that has a few more details on making things work with tiddlyweb: https://github.com/Jermolene/TiddlyWiki5/pull/2371

**Comment by JulianKniephoff** [comment]
I am indeed using TiddlyWiki 5. I just thought from the documentation that `tiddlywebwiki` was a natural place to start playing around with things. Thanks for the hint! :smiley:

**Comment by cdent** [comment]
Which docs are you following? If you let me know I'll try to make them more clear.

They are rather spread around these days, in large part because the tiddlyweb universe hasn't had the full time attention it used to back before 2014. I still try to keep things maintained as people find issues.

I've released a new version of twp.status and twp.atom with your changes.

**Comment by JulianKniephoff** [comment]
[These instructions](https://tank.peermore.com/tanks/tiddlyweb/Installing%20TiddlyWeb) for example and other pages of that site.

Cool, I just tested installing again and everything worked fine, thanks! :smile:

**Comment by cdent** [comment]
> These instructions for example and other pages of that site.

I'll make some quick updates there, thanks.

**Pull request merged**
